apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeapi-bastion.fullname" . }}-host-key
  labels:
    app.kubernetes.io/name: {{ include "kubeapi-bastion.name" . }}
    helm.sh/chart: {{ include "kubeapi-bastion.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  ssh_host_key: {{ (required "SSH Hostkey is required" .Values.ssh.hostKey) | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeapi-bastion.fullname" . }}-user-keys
  labels:
    app.kubernetes.io/name: {{ include "kubeapi-bastion.name" . }}
    helm.sh/chart: {{ include "kubeapi-bastion.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- range $user, $key := .Values.ssh.userKeys }}
  {{ $user }}: {{ $key | b64enc | quote }}
  {{ end }}